### ISSUE TITLE
Potential new "bad" examples: duplication of an existing entry even though the fields are different?

### ISSUE THREAD

**Issue by EskoDijk** [thomas-fossati/draft-cf-reg-update#13]
I was thinking of a registration for an existing entry, where the strings look different but the content-format is effectively duplicating one that already exists.

Maybe cases like
1. Registration with a parameter having the default value "par=default", whereas the content-format without the "par=default" string was already registered.  Effectively they would be the same conent format with duplicate numbers then.
2. Someone registers with "Coding = identity" which is the default coding. This could duplicate an entry in which the "Coding" field is left empty.

**Comment by EskoDijk** [comment]
@thomas-fossati to have a look what you think.

**Comment by thomas-fossati** [comment]
Thanks, Esko.  They both look like good cases to add to our "What could possibly go wrong?" list.
