### ISSUE TITLE
an optimisation for simple cases

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-cf-reg-update#15]
Amanda suggests two separate registration procedures for the 10000-64999 range: 

> _"One other thought about the FCFS range: if the registration consists entirely of a registered media type name in the “Content Type” field, with no parameter names in that field and no “Content Coding” entry, IANA can check for a corresponding media type registration (although it would be helpful to be explicitly told to do so, and to be able to refer to it in the registration procedure table). Maybe that could look something like this:"_

> Range | Registration Procedures | Note
> --|--|--
> 10000-64999 (no parameters or content coding) | FCFS | Corresponding media type registration required
> 10000-64999 (includes parameters and/or content coding) | Expert Review | Lightweight review described in RFC XXXX, Section 5.2.1

**Comment by EskoDijk** [comment]
Seems ok - but it also needs to be checked by IANA that the media type is not already registered somewhere in the CF registry. If it is already registered (possibly with/without parameters, or with/without content coding) then it's again into the Expert Review bucket I think.

**Comment by thomas-fossati** [comment]
> Seems ok - but it also needs to be checked by IANA that the media type is not already registered somewhere in the CF registry. If it is already registered (possibly with/without parameters, or with/without content coding) then it's again into the Expert Review bucket I think.

Yes, if there is any potential conflict with what's already in the registry, the procedure needs to move to Expert Review.

How can we express that concisely and understandably?
