### ISSUE TITLE
Expert review is incompatible with FCFS

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-cf-reg-update#3]
@fpalombini's review:

I have reviewed it and I have one major comment, and I am pretty sure IANA will also complain if they get this as is: it is not ok to add criteria for IANA to check on a FCFS space. As https://datatracker.ietf.org/doc/html/rfc8126#section-4.4 says:
 
    It is also important to understand that First Come First Served
    really has no filtering.  Essentially, any well-formed request is
    accepted.
 
What you are implicitly doing is re-defining a policy that is in practice Expert Review. So my suggestion is to change that range from FCFS to expert review, and specify that these criteria apply for an approval by the DE in that range (the criteria are different from the 0-255 range).

**Comment by thomas-fossati** [comment]
@cabo comment:

Just making that change makes large ranges look the same, even if parts of them have much stronger review requirements (and, unfortunately, processing times) than others.

We should have a pair of terms like “expert quick review” and “deep expert review” to distinguish these with high visibility to the registrants.

**Comment by thomas-fossati** [comment]
> We should have a pair of terms like “expert quick review” and “deep expert review” to distinguish these with high visibility to the registrants.

@cabo, is this what you mean?

OLD:

| Range | Registration Procedures |
|--------|--------|
| 0-255	| Expert Review |
| 256-9999 | IETF Review or IESG Approval |
| 10000-64999 | First Come First Served |
| 65000-65535 | Experimental use (no operational use) |

NEW:

| Range | Registration Procedures |
|--------|--------|
| 0-255	| Expert Review |
| 256-9999 | IETF Review or IESG Approval |
| 10000-64999 | Lightweight Expert Review |
| 65000-65535 | Experimental use (no operational use) |

**Comment by cabo** [comment]
On 2024-11-19, at 21:10, Thomas Fossati ***@***.***> wrote:
> 
> Lightweight Expert Review

Yes.  How about 

Expert Review (Expert Check: FCFS+)

"Expert Review" points to Section 4.5 of 8126, so it is the official statement that IANA follows, and the parenthesis explains some more what procedure the expert follows.

The complement could be:

Expert Review (Full)

Grüße, Carsten
