### ISSUE TITLE
DE check 1 is unclear

### ISSUE THREAD

**Issue by EskoDijk** [thomas-fossati/draft-cf-reg-update#7]
We have the current text:

> 1. The content-type associated with the requested Content-Format must be associated with an already registered CoAP Content-Format;

What is intended with this?  The content-type entry must refer to an already-registered media type? 
(This is also in 2.)

**Comment by thomas-fossati** [comment]
> We have the current text:
> 
> > 1. The content-type associated with the requested Content-Format must be associated with an already registered CoAP Content-Format;
> 
> What is intended with this? The content-type entry must refer to an already-registered media type? (This is also in 2.)

Good catch!  It's a typo (missing "not" && missing "and content coding").  It should say:

> _"The combination of content-type and content coding for which the registration is requested must not be already present in the registry;"_
